@startuml

!$COLOR_PRIMARY_100="#D8DBF3"
!$COLOR_PRIMARY_200="#AFB8F2"
!$COLOR_PRIMARY_300="#8389CF"
!$COLOR_PRIMARY_400="#5A60AB"
!$COLOR_PRIMARY_500="#293286"
!$COLOR_PRIMARY_600="#20256A"
!$COLOR_PRIMARY_700="#161A58"
!$COLOR_PRIMARY_800="#0D114D"
!$COLOR_PRIMARY_900="#0B132B"
!$COLOR_SECONDARY_100="#D6E8FA"
!$COLOR_SECONDARY_200="#AFCFF5"
!$COLOR_SECONDARY_300="#82AAE3"
!$COLOR_SECONDARY_400="#5D85C7"
!$COLOR_SECONDARY_500="#2F57A3"
!$COLOR_SECONDARY_600="#22438C"
!$COLOR_SECONDARY_700="#173175"
!$COLOR_SECONDARY_800="#0E215E"
!$COLOR_SECONDARY_900="#09174E"
!$COLOR_TERTIARY_100="#FCD5DC"
!$COLOR_TERTIARY_200="#FAADC1"
!$COLOR_TERTIARY_300="#F081A9"
!$COLOR_TERTIARY_400="#E15F9B"
!$COLOR_TERTIARY_500="#CE3089"
!$COLOR_TERTIARY_600="#B12381"
!$COLOR_TERTIARY_700="#941876"
!$COLOR_TERTIARY_800="#770F69"
!$COLOR_TERTIARY_900="#62095F"
!$COLOR_FOURTH_100="#FFF5CD"
!$COLOR_FOURTH_200="#FFE89B"
!$COLOR_FOURTH_300="#FFD869"
!$COLOR_FOURTH_400="#FFD156"
!$COLOR_FOURTH_500="#FFC943"
!$COLOR_FOURTH_600="#EF9E11"
!$COLOR_BASIC_100="#FFFFFF"
!$COLOR_BASIC_200="#F9F9F9"
!$COLOR_BASIC_300="#EAEAEA"
!$COLOR_BASIC_400="#DBDADB"
!$COLOR_BASIC_500="#939393"
!$COLOR_BASIC_600="#8F8F8F"
!$COLOR_BASIC_700="#868586"
!$COLOR_BASIC_800="#5C5B5C"
!$COLOR_BASIC_900="#3C3F47"

!$STEREOTYPE_FONT_SIZE ?= 12
!$TECHN_FONT_SIZE ?= 12
!$ELEMENT_FONT_COLOR ?= $COLOR_BASIC_900

!$ARROW_COLOR ?= $COLOR_BASIC_800
!$ARROW_FONT_COLOR ?= $ARROW_COLOR
!$ARROW_FONT_SIZE ?= 12

!$BOUNDARY_COLOR ?= $COLOR_TERTIARY_600
!$BOUNDARY_BG_COLOR ?= "transparent"
!$BOUNDARY_BORDER_STYLE ?= "dashed"

!$ENTERPRISE_BOUNDARY_COLOR ?= $COLOR_FOURTH_600
!$ENTERPRISE_BOUNDARY_BG_COLOR ?= $BOUNDARY_BG_COLOR
!$ENTERPRISE_BOUNDARY_BORDER_STYLE ?= $BOUNDARY_BORDER_STYLE

!$SYSTEM_BOUNDARY_COLOR ?= $COLOR_PRIMARY_600
!$SYSTEM_BOUNDARY_BG_COLOR ?= $BOUNDARY_BG_COLOR
!$SYSTEM_BOUNDARY_BORDER_STYLE ?= $BOUNDARY_BORDER_STYLE

!$CONTAINER_BOUNDARY_COLOR ?= $COLOR_SECONDARY_600
!$CONTAINER_BOUNDARY_BG_COLOR ?= $BOUNDARY_BG_COLOR
!$CONTAINER_BOUNDARY_BORDER_STYLE ?= $BOUNDARY_BORDER_STYLE

!$PERSON_FONT_COLOR ?= $COLOR_BASIC_900
!$PERSON_BG_COLOR ?= $COLOR_FOURTH_500
!$PERSON_BORDER_COLOR ?= $COLOR_FOURTH_600

!$EXTERNAL_PERSON_FONT_COLOR ?= $COLOR_BASIC_900
!$EXTERNAL_PERSON_BG_COLOR ?= $COLOR_FOURTH_100
!$EXTERNAL_PERSON_BORDER_COLOR ?= $COLOR_FOURTH_300

!$SYSTEM_FONT_COLOR ?= $COLOR_BASIC_100
!$SYSTEM_BG_COLOR ?= $COLOR_PRIMARY_500
!$SYSTEM_BORDER_COLOR ?= $COLOR_PRIMARY_700

!$EXTERNAL_SYSTEM_FONT_COLOR ?= $COLOR_BASIC_900
!$EXTERNAL_SYSTEM_BG_COLOR ?= $COLOR_PRIMARY_100
!$EXTERNAL_SYSTEM_BORDER_COLOR ?= $COLOR_PRIMARY_300

!$CONTAINER_FONT_COLOR ?= $COLOR_BASIC_100
!$CONTAINER_BG_COLOR ?= $COLOR_SECONDARY_500
!$CONTAINER_BORDER_COLOR ?= $COLOR_SECONDARY_700

!$EXTERNAL_CONTAINER_FONT_COLOR ?= $COLOR_BASIC_900
!$EXTERNAL_CONTAINER_BG_COLOR ?= $COLOR_SECONDARY_100
!$EXTERNAL_CONTAINER_BORDER_COLOR ?= $COLOR_SECONDARY_300

!$COMPONENT_FONT_COLOR ?= $COLOR_BASIC_100
!$COMPONENT_BG_COLOR ?= $COLOR_TERTIARY_500
!$COMPONENT_BORDER_COLOR ?= $COLOR_TERTIARY_700

!$EXTERNAL_COMPONENT_FONT_COLOR ?= $COLOR_BASIC_900
!$EXTERNAL_COMPONENT_BG_COLOR ?= $COLOR_TERTIARY_100
!$EXTERNAL_COMPONENT_BORDER_COLOR ?= $COLOR_TERTIARY_300

@enduml
